#!/usr/bin/env bash
#This script configures the server's IP resolution for localhost and facebook.com
#Backup the original /etc/hosts file (safety first!)
sudo cp /etc/hosts /etc/hosts.backup

#Update localhost to point to 127.0.0.2
sudo sed -i '/localhost/d' /etc/hosts echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

#Update facebook.com to point to 8.8.8.8 (just for this exercise!)
sudo sed -i '/facebook.com/d' /etc/hosts echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts